modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="CC BY Miraisoft"

[[mods]] #mandatory
modId="sparetheanimals" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Miraisoft's Spare The Animals" #mandatory
displayURL="http://example.com/" #optional
logoFile="sparetheanimals.png" #optional
credits="Thanks for using this mod" #optional
authors="kuuhaku" #optional
description='''
Spare The Animals
You don't want to kill animals? Then this mod is right for you.
This mod makes zombies drop leather, skeletons drop feathers.
'''

[[dependencies.sparetheanimals]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"
	
[[dependencies.sparetheanimals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"